version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-cdn
    restart: always
    ports:
      - "8080:80" # Map port 8080 to access locally
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cdn:/var/cache/nginx:rw
